land-base-path: s3://mojap-land-dev/corporate/matrix/
fail-base-path: s3://mojap-raw-hist-dev/corporate/matrix/fail/
pass-base-path: s3://mojap-raw-hist-dev/corporate/matrix/pass/
log-base-path: s3://mojap-raw-hist-dev/corporate/matrix/log/
compress-data: False
remove-tables-on-pass: True
all-must-pass: True

tables:
  locations:
    required: True
    pattern: null
    metadata: metadata/db_v2/preprod/locations.json
    allow-unexpected-data: True
    allow-missing-cols: True
  bookings:
    required: True
    pattern: null
    metadata: metadata/db_v2/preprod/bookings.json
    allow-unexpected-data: True
    allow-missing-cols: True
